/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package MainUI;

import Backend.DB4OUtil.DB4OUtil;
import Backend.Ecosystem.EcoSystem;
import Backend.Enterprise.Enterprise;
import Backend.Network.Network;
import Backend.Organization.Organization;
import Backend.Role.DonationManager;
import Backend.Role.EmploymentManager;
import Backend.Role.GovernmentSupervisor;
import Backend.Role.HealthManager;
import Backend.Role.HomelessPerson;
import Backend.Role.MealManager;
import Backend.Role.NGOAdmin;
import Backend.Role.PrivateCompanySupervisor;
import Backend.Role.SystemAdminRole;
import Backend.Role.Volunteer;
import Backend.UserAccount.UserAccount;
import FrontEnd.UserRegistration.VolunteerRegistration;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author shubhamgoyal
 */
public class LoginJPanel1 extends javax.swing.JPanel {

    /**
     * Creates new form LoginJPanel1
     */
    private EcoSystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    UserAccount userAccount;
    Enterprise enterprise;
    Organization organization;
    Network network;
    private JPanel displayJPanel;

    public LoginJPanel1(JPanel displayJPanel, EcoSystem system) {
//        this.setUndecorated(true);
        initComponents();
        system = dB4OUtil.retrieveSystem();
        EcoSystem.setInstance(system);
        this.displayJPanel=displayJPanel;
//        loginJPanel.setVisible(true);
//        displayJPanel.setVisible(true);
//        leftPanel.setVisible(false);
//        getRootPane().setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLACK));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginJPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        userNameJTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JLabel();
        btnRegister = new javax.swing.JLabel();

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel3.setText("Homeless Shelter Management");

        jLabel1.setText("User ID");

        userNameJTextField.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        userNameJTextField.setToolTipText("");
        userNameJTextField.setBorder(null);
        userNameJTextField.setCaretColor(new java.awt.Color(255, 255, 255));
        userNameJTextField.setDisabledTextColor(new java.awt.Color(16, 10, 55));
        userNameJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameJTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Password");

        passwordField.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        passwordField.setBorder(null);
        passwordField.setCaretColor(new java.awt.Color(255, 255, 255));
        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });

        loginButton.setBackground(new java.awt.Color(0, 0, 0));
        loginButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        loginButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginButton.setText("LOGIN");
        loginButton.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(236, 113, 107)));
        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginButtonMousePressed(evt);
            }
        });

        btnRegister.setBackground(new java.awt.Color(0, 0, 0));
        btnRegister.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnRegister.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRegister.setText("REGISTER");
        btnRegister.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(236, 113, 107)));
        btnRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRegisterMousePressed(evt);
            }
        });

        javax.swing.GroupLayout loginJPanelLayout = new javax.swing.GroupLayout(loginJPanel);
        loginJPanel.setLayout(loginJPanelLayout);
        loginJPanelLayout.setHorizontalGroup(
            loginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(loginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginJPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(371, 371, 371))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginJPanelLayout.createSequentialGroup()
                        .addGroup(loginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(loginJPanelLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(userNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(loginJPanelLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(403, 403, 403))))
        );
        loginJPanelLayout.setVerticalGroup(
            loginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginJPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addGap(174, 174, 174)
                .addGroup(loginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(loginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void userNameJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameJTextFieldActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void loginButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMousePressed
        // TODO add your handling code here:
        String userName = userNameJTextField.getText();
        char[] passwordCharArray = passwordField.getPassword();
        String password = String.valueOf(passwordCharArray);

        userAccount = system.getUserAccountDirectory().authenticateUser(userName, password);
        enterprise = null;
        organization = null;
        network = null;

        if (userAccount == null) {
            for (Network network : system.getNetworkList()) {
                //Step 2.a: check against each enterprise
                System.out.println("Network name --->> " + network.getName());
                for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                    System.out.println("Enterprise name --->> " + enterprise.getName());
                    userAccount = enterprise.getUserAccountDirectory().authenticateUser(userName, password);
                    network = network;
                    if (userAccount == null) {
                        //Step 3:check against each organization for each enterprise
                        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                            userAccount = organization.getUserAccountDirectory().authenticateUser(userName, password);
                            if (userAccount != null) {
                                enterprise = enterprise;
                                organization = organization;
                                network = network;
                                break;
                            }
                        }

                    } else {
                        enterprise = enterprise;
                        break;
                    }
                    if (organization != null) {
                        break;
                    }
                }
                if (enterprise != null) {
                    break;
                }
                /*if (network != null) {//changed
                    break;
                }*/
            }
        }
        if (userAccount == null) {
            JOptionPane.showMessageDialog(null, "Invalid credentials");
            return;
        } else {
            loginJPanel.setVisible(false);
//            displayJPanel.setVisible(true);
            //            leftPanel.setVisible(true);
            //            btnLogoutLabel.setVisible(true);
            //            btnBackLabel.setVisible(false);
            userNameJTextField.setText("");
            passwordField.setText("");
            changePanel1();
        }
        
    }//GEN-LAST:event_loginButtonMousePressed

        private void changePanel1() {

        if (userAccount != null && userAccount.getRole() != null) {
//            String greetings = "Hi";
            if (userAccount.getRole() instanceof DonationManager) {
//                greetings = greetings + " " + userAccount.getUsername();
                displayJPanel.add("workArea", userAccount.getRole().createWorkArea(displayJPanel, userAccount, organization, enterprise, network, system));
            } else if (userAccount.getRole() instanceof EmploymentManager) {
//                greetings = greetings + " " + userAccount.getUsername();
                displayJPanel.add("workArea", userAccount.getRole().createWorkArea(displayJPanel, userAccount, organization, enterprise, network, system));
            } else if (userAccount.getRole() instanceof GovernmentSupervisor) {
//                greetings = greetings + " " + userAccount.getUsername();
                displayJPanel.add("workArea", userAccount.getRole().createWorkArea(displayJPanel, userAccount, organization, enterprise, network, system));
            } else if (userAccount.getRole() instanceof HealthManager) {
//                greetings = greetings + " " + userAccount.getUsername();
                displayJPanel.add("workArea", userAccount.getRole().createWorkArea(displayJPanel, userAccount, organization, enterprise, network, system));
            } else if (userAccount.getRole() instanceof HomelessPerson) {
//                greetings = greetings + " " + userAccount.getUsername();
                displayJPanel.add("workArea", userAccount.getRole().createWorkArea(displayJPanel, userAccount, organization, enterprise, network, system));
            }else if (userAccount.getRole() instanceof MealManager) {
//                greetings = greetings + " " + userAccount.getUsername();
                displayJPanel.add("workArea", userAccount.getRole().createWorkArea(displayJPanel, userAccount, organization, enterprise, network, system)); 
            }else if (userAccount.getRole() instanceof NGOAdmin) {
//                greetings = greetings + " " + userAccount.getUsername();
                displayJPanel.add("workArea", userAccount.getRole().createWorkArea(displayJPanel, userAccount, organization, enterprise, network, system)); 
            }else if (userAccount.getRole() instanceof PrivateCompanySupervisor) {
//                greetings = greetings + " " + userAccount.getUsername();
                displayJPanel.add("workArea", userAccount.getRole().createWorkArea(displayJPanel, userAccount, organization, enterprise, network, system)); 
//            }else if (userAccount.getRole() instanceof ShelterManager) {
//                greetings = greetings + " " + userAccount.getUsername();
//                displayJPanel.add("workArea", userAccount.getRole().createWorkArea(displayJPanel, userAccount, organization, enterprise, network, system)); 
            }else if (userAccount.getRole() instanceof SystemAdminRole) {
//                greetings = greetings + " " + userAccount.getUsername();
                displayJPanel.add("workArea", userAccount.getRole().createWorkArea(displayJPanel, userAccount, organization, enterprise, network, system)); 
            }else if (userAccount.getRole() instanceof Volunteer) {
//                greetings = greetings + " " + userAccount.getUsername();
                displayJPanel.add("workArea", userAccount.getRole().createWorkArea(displayJPanel, userAccount, organization, enterprise, network, system)); 
//            }else if (userAccount.getRole() instanceof SceneManager) {
//                greetings = greetings + " " + userAccount.getUsername();
//                displayJPanel.add("workArea", userAccount.getRole().createWorkArea(displayJPanel, userAccount, organization, enterprise, network, system)); 
//            }else if (userAccount.getRole() instanceof VoluntaryUnitAdmin) {
//                greetings = greetings + " " + userAccount.getUsername();
//                displayJPanel.add("workArea", userAccount.getRole().createWorkArea(displayJPanel, userAccount, organization, enterprise, network, system)); 
            }else {
//                greetings = greetings + " " + userAccount.getUsername();
                displayJPanel.add("workArea", userAccount.getRole().createWorkArea(displayJPanel, userAccount, organization, enterprise, network, system));
            }
//            greetingUserLabel.setText(greetings + " !!!");
//            displayJPanel.getLayout()
            CardLayout layout = (CardLayout) displayJPanel.getLayout();
            layout.next(displayJPanel);
        }

    }
    
    
    private void btnRegisterMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterMousePressed
        // TODO add your handling code here:
        VolunteerRegistration panel = new VolunteerRegistration(displayJPanel, system);
        
        userNameJTextField.setText("");
        passwordField.setText("");
        displayJPanel.add("workArea", panel);
        CardLayout layout = (CardLayout) displayJPanel.getLayout();
        layout.next(displayJPanel);
        
    }//GEN-LAST:event_btnRegisterMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel loginButton;
    private javax.swing.JPanel loginJPanel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField userNameJTextField;
    // End of variables declaration//GEN-END:variables
}
